"""
NAME
    app_versions.py - Central app version constants.
"""

APP_CAN_BRIDGE_NAME = "can_nt_bridge"
APP_BRIDGE_CLI_NAME = "bridge_cli"
APP_BRINGUP_UI_NAME = "bringup_ui"
APP_CAN_TOPOLOGY_NAME = "can_topology_editor"
APP_ROBOT_NAME = "robot_bringup"


def _version_string(major: int, minor: int, patch: int) -> str:
    return f"{major}.{minor}.{patch}"


VERSION_CAN_BRIDGE_MAJOR = 1
VERSION_CAN_BRIDGE_MINOR = 0
VERSION_CAN_BRIDGE_PATCH = 0
VERSION_CAN_BRIDGE = _version_string(
    VERSION_CAN_BRIDGE_MAJOR,
    VERSION_CAN_BRIDGE_MINOR,
    VERSION_CAN_BRIDGE_PATCH,
)

VERSION_BRIDGE_CLI_MAJOR = 1
VERSION_BRIDGE_CLI_MINOR = 0
VERSION_BRIDGE_CLI_PATCH = 0
VERSION_BRIDGE_CLI = _version_string(
    VERSION_BRIDGE_CLI_MAJOR,
    VERSION_BRIDGE_CLI_MINOR,
    VERSION_BRIDGE_CLI_PATCH,
)

VERSION_BRINGUP_UI_MAJOR = 1
VERSION_BRINGUP_UI_MINOR = 0
VERSION_BRINGUP_UI_PATCH = 0
VERSION_BRINGUP_UI = _version_string(
    VERSION_BRINGUP_UI_MAJOR,
    VERSION_BRINGUP_UI_MINOR,
    VERSION_BRINGUP_UI_PATCH,
)

VERSION_CAN_TOPOLOGY_MAJOR = 1
VERSION_CAN_TOPOLOGY_MINOR = 0
VERSION_CAN_TOPOLOGY_PATCH = 0
VERSION_CAN_TOPOLOGY = _version_string(
    VERSION_CAN_TOPOLOGY_MAJOR,
    VERSION_CAN_TOPOLOGY_MINOR,
    VERSION_CAN_TOPOLOGY_PATCH,
)

VERSION_ROBOT_MAJOR = 1
VERSION_ROBOT_MINOR = 0
VERSION_ROBOT_PATCH = 0
VERSION_ROBOT = _version_string(
    VERSION_ROBOT_MAJOR,
    VERSION_ROBOT_MINOR,
    VERSION_ROBOT_PATCH,
)

VERSION_HEADER = "Version"
VERSION_SEPARATOR = ": "

APP_VERSION_ORDER = (
    APP_CAN_BRIDGE_NAME,
    APP_BRIDGE_CLI_NAME,
    APP_BRINGUP_UI_NAME,
    APP_CAN_TOPOLOGY_NAME,
    APP_ROBOT_NAME,
)

VERSIONS = {
    APP_CAN_BRIDGE_NAME: VERSION_CAN_BRIDGE,
    APP_BRIDGE_CLI_NAME: VERSION_BRIDGE_CLI,
    APP_BRINGUP_UI_NAME: VERSION_BRINGUP_UI,
    APP_CAN_TOPOLOGY_NAME: VERSION_CAN_TOPOLOGY,
    APP_ROBOT_NAME: VERSION_ROBOT,
}


def format_version_line(app_name: str, version: str) -> str:
    """
    NAME
        format_version_line - Build a standard version line.
    """
    return f"{app_name}{VERSION_SEPARATOR}{version}"
