"""
NAME
    constants.py - Shared symbolic constants for the stage-1 evidence-fusion core.
"""

SCHEMA_VERSION_1 = 1

MAJOR_TYPE_OBSERVATION = "observation"
MAJOR_TYPE_SOURCE_STATE = "source_state"
MAJOR_TYPE_CONTEXT_REVISION = "context_revision"
MAJOR_TYPE_CLOCK_TICK = "clock_tick"
MAJOR_TYPE_RETRACTION = "retraction"
MAJOR_TYPE_RECOVERY = "recovery"

MAJOR_TYPES = (
    MAJOR_TYPE_OBSERVATION,
    MAJOR_TYPE_SOURCE_STATE,
    MAJOR_TYPE_CONTEXT_REVISION,
    MAJOR_TYPE_CLOCK_TICK,
    MAJOR_TYPE_RETRACTION,
    MAJOR_TYPE_RECOVERY,
)

SCOPE_DEVICE = "device"
SCOPE_SYSTEM = "system"
SCOPE_CONTEXT = "context"
SCOPE_SOURCE = "source"

SCOPES = (
    SCOPE_DEVICE,
    SCOPE_SYSTEM,
    SCOPE_CONTEXT,
    SCOPE_SOURCE,
)

PRIORITY_HINT_DEFAULT = "default"
PRIORITY_HINTS = (PRIORITY_HINT_DEFAULT,)

QUEUE_LANE_SOURCE_HEALTH = "source_health"
QUEUE_LANE_CONTEXT = "context"
QUEUE_LANE_FAULT_EVENT = "fault_event"
QUEUE_LANE_INTERACTIVE_MANUAL = "interactive_manual"
QUEUE_LANE_PERIODIC_RUNTIME = "periodic_runtime"
QUEUE_LANE_PERIODIC_PASSIVE = "periodic_passive"
QUEUE_LANE_CLOCK_TICK = "clock_tick"
QUEUE_LANE_OFFLINE_REPLAY = "offline_replay"

QUEUE_LANES_IN_PRIORITY_ORDER = (
    QUEUE_LANE_SOURCE_HEALTH,
    QUEUE_LANE_CONTEXT,
    QUEUE_LANE_FAULT_EVENT,
    QUEUE_LANE_INTERACTIVE_MANUAL,
    QUEUE_LANE_PERIODIC_RUNTIME,
    QUEUE_LANE_PERIODIC_PASSIVE,
    QUEUE_LANE_CLOCK_TICK,
    QUEUE_LANE_OFFLINE_REPLAY,
)

RESULT_CODE_ACCEPTED = "accepted"
RESULT_CODE_DUPLICATE = "duplicate"
RESULT_CODE_REJECTED = "rejected"

DROP_REASON_NONE = ""
DROP_REASON_DUPLICATE = "duplicate"
DROP_REASON_INVALID = "invalid"

AFFECTED_SCOPE_DEVICE = "device"
AFFECTED_SCOPE_SYSTEM = "system"
AFFECTED_SCOPE_CONTEXT = "context"
AFFECTED_SCOPE_SOURCE = "source"
AFFECTED_SCOPE_UNKNOWN_DEVICE = "unknown_device"

SOURCE_TYPE_RUNTIME = "runtime"
SOURCE_TYPE_PASSIVE_CAN = "passive_can"
SOURCE_TYPE_SYSTEM_CLOCK = "system_clock"
SOURCE_TYPE_CONSOLE = "console"
SOURCE_TYPE_MANUAL = "manual"
SOURCE_TYPE_DSL = "dsl"
SOURCE_TYPE_CONTEXT = "context"

SOURCE_TYPES_USING_RUNTIME_LANE = (
    SOURCE_TYPE_RUNTIME,
    SOURCE_TYPE_MANUAL,
    SOURCE_TYPE_DSL,
)

SOURCE_TYPES_USING_PASSIVE_LANE = (
    SOURCE_TYPE_PASSIVE_CAN,
    SOURCE_TYPE_CONSOLE,
)

SNAPSHOT_ID_PREFIX = "snapshot"
EVALUATION_ID_PREFIX = "evaluation"
UNKNOWN_DEVICE_PREFIX = "unknown"

FRESHNESS_STATE_CURRENT = "current"
FRESHNESS_STATE_DECAYING = "decaying"
FRESHNESS_STATE_EXPIRED = "expired"
FRESHNESS_STATE_HISTORICAL = "historical"

FRESHNESS_POLICY_NAME_RUNTIME = "runtime_default"
FRESHNESS_POLICY_NAME_PASSIVE = "passive_default"
FRESHNESS_POLICY_NAME_SOURCE_STATE = "source_state_default"
FRESHNESS_POLICY_NAME_CONTEXT = "context_default"
FRESHNESS_POLICY_NAME_CLOCK_TICK = "clock_tick_default"

POLICY_RUNTIME_FULL_STRENGTH_MS = 250
POLICY_RUNTIME_HARD_EXPIRY_MS = 2000
POLICY_RUNTIME_HISTORICAL_RETENTION_MS = 10000
POLICY_RUNTIME_CORRELATION_CAP = 2

POLICY_PASSIVE_FULL_STRENGTH_MS = 1000
POLICY_PASSIVE_HARD_EXPIRY_MS = 12000
POLICY_PASSIVE_HISTORICAL_RETENTION_MS = 60000
POLICY_PASSIVE_CORRELATION_CAP = 2

POLICY_SOURCE_STATE_FULL_STRENGTH_MS = 1000
POLICY_SOURCE_STATE_HARD_EXPIRY_MS = 12000
POLICY_SOURCE_STATE_HISTORICAL_RETENTION_MS = 60000
POLICY_SOURCE_STATE_CORRELATION_CAP = 1

POLICY_CONTEXT_FULL_STRENGTH_MS = 0
POLICY_CONTEXT_HARD_EXPIRY_MS = 0
POLICY_CONTEXT_HISTORICAL_RETENTION_MS = 1
POLICY_CONTEXT_CORRELATION_CAP = 1

POLICY_CLOCK_TICK_FULL_STRENGTH_MS = 0
POLICY_CLOCK_TICK_HARD_EXPIRY_MS = 0
POLICY_CLOCK_TICK_HISTORICAL_RETENTION_MS = 1
POLICY_CLOCK_TICK_CORRELATION_CAP = 1

PAYLOAD_KEY_RETRACTED_BLOCK_ID = "retractedBlockId"
SYSTEM_STATE_KEY_ACTIVE_SOURCE_SESSIONS = "activeSourceSessions"
SYSTEM_STATE_KEY_RETRACTED_BLOCK_IDS = "retractedBlockIds"
SYSTEM_STATE_KEY_OBSERVATION_STATE_COUNTS = "observationStateCounts"

ZERO_INT = 0
ONE_INT = 1
ZERO_FLOAT = 0.0
ONE_FLOAT = 1.0
MEDIUM_FLOAT = 0.5
HIGH_CONFIDENCE_THRESHOLD = 0.75
MEDIUM_CONFIDENCE_THRESHOLD = 0.4
CONFLICT_SUPPORT_THRESHOLD = 0.35
CONFLICT_MARGIN_THRESHOLD = 0.2
NEAR_ZERO_THRESHOLD = 0.000001

PAYLOAD_KEY_DIMENSION = "dimension"
PAYLOAD_KEY_ASSERTION = "assertion"
PAYLOAD_KEY_POLARITY = "polarity"
PAYLOAD_KEY_CLAIM_STRENGTH = "claimStrength"
PAYLOAD_KEY_SPECIFICITY = "specificity"
PAYLOAD_KEY_DIRECTNESS = "directness"
PAYLOAD_KEY_QUALITY = "quality"
PAYLOAD_KEY_SOURCE_HEALTH = "sourceHealth"
PAYLOAD_KEY_BASE_RELIABILITY = "baseReliability"
PAYLOAD_KEY_INDEPENDENCE_GROUP = "independenceGroup"
PAYLOAD_KEY_REASON_CODE = "reasonCode"

PAYLOAD_POLARITY_SUPPORT = "support"

DIMENSION_EXISTENCE = "existence"
DIMENSION_COMMUNICATION = "communication"
DIMENSION_OPERABILITY = "operability"
DIMENSION_IDENTITY = "identity"

DIMENSIONS = (
    DIMENSION_EXISTENCE,
    DIMENSION_COMMUNICATION,
    DIMENSION_OPERABILITY,
    DIMENSION_IDENTITY,
)

EXISTENCE_PRESENT = "PRESENT"
EXISTENCE_ABSENT = "ABSENT"
EXISTENCE_UNKNOWN = "UNKNOWN"
COMMUNICATION_HEALTHY = "HEALTHY"
COMMUNICATION_DEGRADED = "DEGRADED"
COMMUNICATION_FAILED = "FAILED"
COMMUNICATION_UNKNOWN = "UNKNOWN"
OPERABILITY_WORKING = "WORKING"
OPERABILITY_DEGRADED = "DEGRADED"
OPERABILITY_FAILED = "FAILED"
OPERABILITY_UNPROVEN = "UNPROVEN"
OPERABILITY_UNKNOWN = "UNKNOWN"
IDENTITY_MATCHING = "MATCHING"
IDENTITY_MISMATCHED = "MISMATCHED"
IDENTITY_UNKNOWN = "UNKNOWN"

DIMENSION_ALLOWED_VALUES = {
    DIMENSION_EXISTENCE: (
        EXISTENCE_PRESENT,
        EXISTENCE_ABSENT,
        EXISTENCE_UNKNOWN,
    ),
    DIMENSION_COMMUNICATION: (
        COMMUNICATION_HEALTHY,
        COMMUNICATION_DEGRADED,
        COMMUNICATION_FAILED,
        COMMUNICATION_UNKNOWN,
    ),
    DIMENSION_OPERABILITY: (
        OPERABILITY_WORKING,
        OPERABILITY_DEGRADED,
        OPERABILITY_FAILED,
        OPERABILITY_UNPROVEN,
        OPERABILITY_UNKNOWN,
    ),
    DIMENSION_IDENTITY: (
        IDENTITY_MATCHING,
        IDENTITY_MISMATCHED,
        IDENTITY_UNKNOWN,
    ),
}

CONFIDENCE_HIGH = "HIGH"
CONFIDENCE_MEDIUM = "MEDIUM"
CONFIDENCE_LOW = "LOW"

OVERALL_HEALTHY = "HEALTHY"
OVERALL_CAUTION = "CAUTION"
OVERALL_PROBABLE_FAULT = "PROBABLE_FAULT"
OVERALL_IDENTITY_FAULT = "IDENTITY_FAULT"
OVERALL_FAILED = "FAILED"
OVERALL_UNKNOWN = "UNKNOWN"

SYSTEM_STATE_KEY_DEVICE_RESULTS = "deviceShadowResults"
SYSTEM_STATE_KEY_SYSTEM_RESULTS = "systemShadowResults"
SYSTEM_STATE_KEY_DIFF_COUNT = "shadowDiffCount"
