from __future__ import annotations

"""
NAME
    constants.py - Shared constants for the passive discovery PoC.

DESCRIPTION
    Centralizes string, numeric, and schema constants so executable paths avoid
    inline literals.
"""

APP_NAME = "passive_discovery_poc"
APP_DESCRIPTION = "Offline-first passive CAN device discovery proof of concept."
DEFAULT_LIVE_DURATION_SEC = 5.0
DEFAULT_MAX_FRAME_HISTORY = 4096
DEFAULT_CAN_BITRATE = 1_000_000
DEFAULT_SLCAN_INTERFACE = "slcan"
DEFAULT_AUTO_MATCH = "CANable"
DEFAULT_REV_AUTO_MATCH = "REV"
DEFAULT_SERIAL_TIMEOUT_SEC = 0.1
DEFAULT_REV_SERIAL_BAUD = 115200

SOURCE_KIND_PCAPNG = "pcapng"
SOURCE_KIND_CANDUMP = "candump"
SOURCE_KIND_CTRE_HTTP = "ctre_http"
SOURCE_KIND_PROFILE = "profile"
SOURCE_KIND_TOPOLOGY = "topology"
SOURCE_KIND_RIO_CONSOLE_LOG = "rio_console_log"
SOURCE_KIND_LIVE_SLCAN = "live_slcan"
SOURCE_KIND_LIVE_REV_SERIAL = "live_rev_serial"
SOURCE_KIND_CAPTURE_AUTO = "capture_auto"

SOURCE_CLASS_FRAME = "frame"
SOURCE_CLASS_ENRICHMENT = "enrichment"

SOURCE_MODE_RECORDED = "recorded"
SOURCE_MODE_LIVE = "live"

INTERFACE_CAN = "CAN"

ROLE_DEVICE_EMITTED_PRIMARY_STATUS = "DEVICE_EMITTED_PRIMARY_STATUS"
ROLE_DEVICE_EMITTED_SECONDARY_STATUS = "DEVICE_EMITTED_SECONDARY_STATUS"
ROLE_DEVICE_EMITTED_HEARTBEAT_HOUSEKEEPING = "DEVICE_EMITTED_HEARTBEAT_HOUSEKEEPING"
ROLE_CONTROLLER_EMITTED_COMMAND = "CONTROLLER_EMITTED_COMMAND"
ROLE_CONTROLLER_EMITTED_POLL = "CONTROLLER_EMITTED_POLL"
ROLE_SHARED_BUS_CONTROL = "SHARED_BUS_CONTROL"
ROLE_UNKNOWN = "UNKNOWN"

HEALTH_UNKNOWN = "unknown"
HEALTH_LIMITED = "limited"
HEALTH_GOOD_EVIDENCE = "good_evidence"
HEALTH_DEGRADED = "degraded"
HEALTH_FAULT_INDICATED = "fault_indicated"

PRESENCE_HIGH = "high"
PRESENCE_MEDIUM = "medium"
PRESENCE_LOW = "low"
PRESENCE_NONE = "none"
PRESENCE_UNCERTAIN = "uncertain"

EXPECTED_STATUS_OBSERVED = "observed"
EXPECTED_STATUS_MISSING = "missing"
EXPECTED_STATUS_UNEXPECTED = "unexpected"
EXPECTED_STATUS_UNCERTAIN = "uncertain"

MODEL_UNKNOWN = "Unknown"
BUS_UNKNOWN = ""
PROFILE_NODE_UNKNOWN = ""

JSON_INDENT = 2
ENCODING_UTF8 = "utf-8"
ERR_REPLACE = "replace"

EXT_PCAPNG = ".pcapng"
EXT_JSON = ".json"
EXT_LOG = ".log"
EXT_TXT = ".txt"

DEFAULT_OUTPUT_SUFFIX = ".passive_discovery.json"
DEFAULT_BRINGUP_PROFILE_PATH = "src/main/deploy/bringup_system.json"

CAN_EXT_ID_MAX = 0x1FFFFFFF
CAN_STD_ID_MAX = 0x7FF
LINKTYPE_CAN_SOCKETCAN = 227

PCAPNG_BLOCK_SECTION_HEADER = 0x0A0D0D0A
PCAPNG_BLOCK_INTERFACE_DESCRIPTION = 0x00000001
PCAPNG_BLOCK_ENHANCED_PACKET = 0x00000006

SOCKETCAN_EFF_FLAG = 0x80000000
SOCKETCAN_RTR_FLAG = 0x40000000
SOCKETCAN_ERR_FLAG = 0x20000000
SOCKETCAN_ID_MASK = 0x1FFFFFFF

SOCKETCAN_HEADER_LEN = 8
STRUCT_ENDIAN_BIG = ">"
STRUCT_ENDIAN_LITTLE = "<"

ONE_MILLION = 1_000_000.0
INT_ZERO = 0
INT_ONE = 1
INT_TWO = 2
INT_THREE = 3
INT_FOUR = 4
INT_EIGHT = 8
FLOAT_ZERO = 0.0

RATE_HIGH_MIN_HZ = 40.0
RATE_HIGH_MAX_HZ = 120.0
RATE_SECONDARY_MIN_HZ = 3.0
RATE_SECONDARY_MAX_HZ = 20.0
RATE_HEARTBEAT_MAX_HZ = 3.0

STABILITY_MAX_REL_STDDEV = 0.35
CONSTANT_PAYLOAD_VARIATION_MAX = 2

REV_MANUFACTURER = 5
CTRE_MANUFACTURER = 4
ROBORIO_MANUFACTURER = 1
CTRE_DEVICE_TYPE_PIGEON_PASSIVE = 21
CTRE_DEVICE_TYPE_PIGEON_CANONICAL = 6

DEVICE_TYPE_BROADCAST = 0
DEVICE_TYPE_MOTOR_CONTROLLER = 2
DEVICE_TYPE_POWER_DISTRIBUTION = 8

REV_COMMAND_API_CLASS = 0
REV_COMMAND_INDEX_DUTY = 2
REV_COMMAND_INDEX_VOLTAGE = 5
REV_COMMAND_INDEX_CURRENT = 6

CTRE_HTTP_ACTION_GET_DEVICES = "getdevices"
CTRE_HTTP_ACTION_DECORATED_SELFTEST = "decoratedselftest"
CTRE_HTTP_ACTION_GET_VERSION = "getversion"
CTRE_HTTP_CANBUS_RIO = "rio"

RUN_METADATA_KEY = "run"
DEVICES_KEY = "devices"
FAMILIES_KEY = "families"
UNKNOWN_TRAFFIC_KEY = "unknownTraffic"
EXPECTED_MISSING_KEY = "expectedMissingDevices"
UNEXPECTED_DEVICES_KEY = "unexpectedDevices"
WARNINGS_KEY = "warnings"
ENRICHMENTS_KEY = "enrichments"

RUN_METADATA_SOURCE_DIAGNOSTICS = "sourceDiagnostics"
DIAGNOSTIC_SOURCE_KIND = "sourceKind"
DIAGNOSTIC_RESOLVED_CHANNEL = "resolvedChannel"
DIAGNOSTIC_RESOLVED_PORT = "resolvedPort"
DIAGNOSTIC_RAW_BYTES_RECEIVED = "rawBytesReceived"
DIAGNOSTIC_RAW_RECORD_COUNT = "rawRecordCount"
DIAGNOSTIC_PARSED_RECORD_COUNT = "parsedRecordCount"
DIAGNOSTIC_NORMALIZED_FRAME_COUNT = "normalizedFrameCount"
DIAGNOSTIC_BUS_MESSAGE_COUNT = "busMessageCount"

TOPOLOGY_RECORD_KIND_NODE = "topology_node"
TOPOLOGY_RECORD_KIND_EDGE = "topology_edge"
TOPOLOGY_NODE_COUNT_KEY = "nodeCount"
TOPOLOGY_EDGE_COUNT_KEY = "edgeCount"

DEFAULT_CONSOLE_RULES_PATH = "tools/can_nt/console_rules.json"
CONSOLE_RECORD_KIND = "console_event"
CONSOLE_UNRESOLVED_RECORD_KIND = "console_unresolved"
CONSOLE_CONFIDENCE_HIGH = "high"
CONSOLE_CONFIDENCE_MEDIUM = "medium"
CONSOLE_CONFIDENCE_LOW = "low"
CONSOLE_CATEGORY_DEVICE = "device"
CONSOLE_CATEGORY_SYSTEM = "system"
CONSOLE_EVIDENCE_UNRESOLVED = "UNRESOLVED_CONSOLE_CAN_HINT"
CONSOLE_KEYWORD_CAN = "can"
CONSOLE_KEYWORD_SPARK = "spark"
CONSOLE_KEYWORD_PDP = "pdp"
CONSOLE_KEYWORD_PDH = "pdh"
CONSOLE_KEYWORD_TALON = "talon"
CONSOLE_KEYWORD_PIGEON = "pigeon"
CONSOLE_KEYWORD_DEVICE = "device"
CONSOLE_HINT_KEYWORDS = (
    CONSOLE_KEYWORD_CAN,
    CONSOLE_KEYWORD_SPARK,
    CONSOLE_KEYWORD_PDP,
    CONSOLE_KEYWORD_PDH,
    CONSOLE_KEYWORD_TALON,
    CONSOLE_KEYWORD_PIGEON,
    CONSOLE_KEYWORD_DEVICE,
)

TABLE_COL_KEY = "device"
TABLE_COL_DEVICE = "device"
TABLE_COL_PRESENCE = "presence"
TABLE_COL_PRESENCE_SCORE = "presenceScore"
TABLE_COL_INVENTORY_SCORE = "inventoryScore"
TABLE_COL_HEALTH = "health"
TABLE_COL_HEALTH_SCORE = "healthScore"
TABLE_COL_EXPECTED = "expected"
TABLE_COL_SOURCES = "sources"
TABLE_COL_EVIDENCE = "evidenceFamilies"

README_FILE = "README.md"

CANDUMP_LINE_REGEX = r"^\((?P<ts>[0-9]+\.[0-9]+)\)\s+(?P<chan>\S+)\s+(?P<id>[0-9A-Fa-f]{1,8})#(?P<data>[0-9A-Fa-f]*)\s*(?P<dir>[RT])?\s*$"

REV_SERIAL_RECORD_SEPARATOR = "\r"
REV_SERIAL_REPLACE_LF = "\n"

SERIAL_MATCH_FIELD_DESCRIPTION = "description"
SERIAL_MATCH_FIELD_MANUFACTURER = "manufacturer"
SERIAL_MATCH_FIELD_PRODUCT = "product"
SERIAL_MATCH_FIELD_INTERFACE = "interface"
SERIAL_MATCH_FIELD_HWID = "hwid"

REV_SERIAL_MATCH_FIELDS = (
    SERIAL_MATCH_FIELD_DESCRIPTION,
    SERIAL_MATCH_FIELD_MANUFACTURER,
    SERIAL_MATCH_FIELD_PRODUCT,
    SERIAL_MATCH_FIELD_INTERFACE,
    SERIAL_MATCH_FIELD_HWID,
)

REV_SERIAL_AUTO_MATCH_CANDIDATES = (
    "REV",
    "Spark",
    "SPARK",
)

AUTO_PORT_SENTINEL = "auto"
