"""
NAME
    robot_test_dsl - Host-side parser/compiler/validator for the robot test DSL.

DESCRIPTION
    Provides source parsing, normalized JSON compilation, and validation for the
    execution DSL defined by ROBOT_DIAGNOSTIC_TEST_DSL_SPEC_V0_3.md.
"""

from .model import (
    DSL_SCHEMA_VERSION,
    DEFAULT_TEST_SET,
    BUILTIN_TIMER_NAME,
    RobotTestDslStore,
    RobotTestDslEntry,
    RobotTestDslNormalized,
    RobotTestDslDeviceRef,
    RobotTestDslReference,
    RobotTestDslLiteral,
    RobotTestDslCondition,
    RobotTestDslSetStatement,
    RobotTestDslClearStatement,
    RobotTestDslUnsafeExit,
    RobotTestDslPhase,
)
from .compiler import compile_source, compile_store_sources
from .serializer import store_from_payload, store_to_payload, source_hash
from .validator import ValidationIssue, ValidationResult, validate_entry, validate_store
from .service import (
    create_blank_test_in_root_payload,
    copy_external_library_test_into_root_payload,
    copy_test_into_root_payload,
    config_library_test_runnable_map,
    delete_external_library_test,
    delete_test_from_root_payload,
    DslImportResult,
    DslServiceError,
    cleanup_stale_tests_in_store,
    device_catalog,
    device_type_alias_catalog,
    import_test_into_config_library,
    import_test_into_external_library,
    import_test_into_root_payload,
    external_library_test_runnable_map,
    issue_detail,
    issue_line_excerpt,
    list_external_library_test_names,
    rename_external_library_test,
    rename_test_in_root_payload,
    render_validation_text,
    read_external_library_test_source,
    profile_test_runnable_map,
    resolve_profile_device_dsl_type,
    resolve_global_library_test_names,
    resolve_profile_test_names,
    resolve_runnable_profile_test_names,
    resolve_profile_test_set_name,
    signal_catalog,
    store_from_root_payload,
    update_test_source_in_root_payload,
    validate_store_for_profile,
    write_test_source_into_config_library,
    write_test_source_into_profile,
    write_store_to_root_payload,
)

__all__ = [
    "DSL_SCHEMA_VERSION",
    "DEFAULT_TEST_SET",
    "BUILTIN_TIMER_NAME",
    "RobotTestDslStore",
    "RobotTestDslEntry",
    "RobotTestDslNormalized",
    "RobotTestDslDeviceRef",
    "RobotTestDslReference",
    "RobotTestDslLiteral",
    "RobotTestDslCondition",
    "RobotTestDslSetStatement",
    "RobotTestDslClearStatement",
    "RobotTestDslUnsafeExit",
    "RobotTestDslPhase",
    "compile_source",
    "compile_store_sources",
    "store_from_payload",
    "store_to_payload",
    "source_hash",
    "ValidationIssue",
    "ValidationResult",
    "validate_entry",
    "validate_store",
    "create_blank_test_in_root_payload",
    "copy_external_library_test_into_root_payload",
    "copy_test_into_root_payload",
    "config_library_test_runnable_map",
    "delete_external_library_test",
    "delete_test_from_root_payload",
    "DslImportResult",
    "DslServiceError",
    "cleanup_stale_tests_in_store",
    "device_catalog",
    "device_type_alias_catalog",
    "import_test_into_config_library",
    "import_test_into_external_library",
    "import_test_into_root_payload",
    "external_library_test_runnable_map",
    "issue_detail",
    "issue_line_excerpt",
    "list_external_library_test_names",
    "rename_external_library_test",
    "rename_test_in_root_payload",
    "render_validation_text",
    "read_external_library_test_source",
    "profile_test_runnable_map",
    "resolve_profile_device_dsl_type",
    "resolve_global_library_test_names",
    "resolve_profile_test_names",
    "resolve_runnable_profile_test_names",
    "resolve_profile_test_set_name",
    "signal_catalog",
    "store_from_root_payload",
    "update_test_source_in_root_payload",
    "validate_store_for_profile",
    "write_test_source_into_config_library",
    "write_test_source_into_profile",
    "write_store_to_root_payload",
]
