"""
NAME
    config_codes.py - Status codes for CONFIG facility.
"""

from tools.can_nt.status.status_catalog import FAC, MSG, SEV
from tools.can_nt.status.status_encode import code

SS__CONFIG__NOT_LOADED = code(SEV.ERROR, FAC.CONFIG, MSG.CONFIG.NOT_LOADED)
SS__CONFIG__INVALID = code(SEV.ERROR, FAC.CONFIG, MSG.CONFIG.INVALID)
SS__CONFIG__SAVED = code(SEV.INFO, FAC.CONFIG, MSG.CONFIG.SAVED)
SS__CONFIG__MERGED = code(SEV.INFO, FAC.CONFIG, MSG.CONFIG.MERGED)
SS__CONFIG__IMPORTED = code(SEV.INFO, FAC.CONFIG, MSG.CONFIG.IMPORTED)
SS__CONFIG__VALID = code(SEV.SUCCESS, FAC.CONFIG, MSG.CONFIG.VALID)
SS__CONFIG__PROFILE_REQUIRED = code(SEV.ERROR, FAC.CONFIG, MSG.CONFIG.PROFILE_REQUIRED)
SS__CONFIG__DUPLICATE_LABEL = code(SEV.ERROR, FAC.CONFIG, MSG.CONFIG.DUPLICATE_LABEL)
SS__CONFIG__MISSING_DEVICE = code(SEV.ERROR, FAC.CONFIG, MSG.CONFIG.MISSING_DEVICE)
