"""
NAME
    network_codes.py - Status codes for NETWORK facility.
"""

from tools.can_nt.status.status_catalog import FAC, MSG, SEV
from tools.can_nt.status.status_encode import code

SS__NETWORK__NOT_CONNECTED = code(SEV.WARNING, FAC.NETWORK, MSG.NETWORK.NOT_CONNECTED)
SS__NETWORK__COMMAND_SEND_FAILED = code(SEV.ERROR, FAC.NETWORK, MSG.NETWORK.COMMAND_SEND_FAILED)
SS__NETWORK__HANDSHAKE_FAILED = code(SEV.ERROR, FAC.NETWORK, MSG.NETWORK.HANDSHAKE_FAILED)
SS__NETWORK__CONNECT_FAILED = code(SEV.ERROR, FAC.NETWORK, MSG.NETWORK.CONNECT_FAILED)
SS__NETWORK__ROBOT_UNAVAILABLE = code(SEV.ERROR, FAC.NETWORK, MSG.NETWORK.ROBOT_UNAVAILABLE)
SS__NETWORK__TIMEOUT = code(SEV.ERROR, FAC.NETWORK, MSG.NETWORK.TIMEOUT)

STATUS_MESSAGES = {
    SS__NETWORK__NOT_CONNECTED: "Robot not connected.",
    SS__NETWORK__COMMAND_SEND_FAILED: "Failed to send command.",
    SS__NETWORK__HANDSHAKE_FAILED: "Handshake failed.",
    SS__NETWORK__CONNECT_FAILED: "Failed to connect.",
    SS__NETWORK__ROBOT_UNAVAILABLE: "Robot unavailable.",
    SS__NETWORK__TIMEOUT: "Command timed out.",
}
