"""
NAME
    network_codes.py - Status codes for NETWORK facility.
"""

from tools.can_nt.status.status_catalog import FAC, MSG, SEV
from tools.can_nt.status.status_encode import code

SS__NETWORK__NOT_CONNECTED = code(SEV.WARNING, FAC.NETWORK, MSG.NETWORK.NOT_CONNECTED)
SS__NETWORK__COMMAND_SEND_FAILED = code(SEV.ERROR, FAC.NETWORK, MSG.NETWORK.COMMAND_SEND_FAILED)
SS__NETWORK__HANDSHAKE_FAILED = code(SEV.ERROR, FAC.NETWORK, MSG.NETWORK.HANDSHAKE_FAILED)
SS__NETWORK__CONNECT_FAILED = code(SEV.ERROR, FAC.NETWORK, MSG.NETWORK.CONNECT_FAILED)
SS__NETWORK__ROBOT_UNAVAILABLE = code(SEV.ERROR, FAC.NETWORK, MSG.NETWORK.ROBOT_UNAVAILABLE)
SS__NETWORK__TIMEOUT = code(SEV.ERROR, FAC.NETWORK, MSG.NETWORK.TIMEOUT)
